<?php

/**
 * @file
 * Calibr8 Cookie Compliance module.
 */

use Drupal\Core\Template\Attribute;
use Drupal\Core\StringTranslation\TranslatableMarkup;
use Drupal\Component\Utility\Xss;

/**
 * Implements hook_page_attachments().
 */
function calibr8_cookie_compliance_page_attachments(&$attachments) {
  // Get config.
  $config = \Drupal::config('calibr8_cookie_compliance.settings');

  $admin_context = \Drupal::service('router.admin_context');
  if ($admin_context->isAdminRoute() || empty($config) || !isset($config->get('notification_message')['value'])) {
    return;
  }

  // Create render array.
  $html_info = [
    '#theme' => 'calibr8_cookie_info',
    '#attributes' => new Attribute([
      'id' => 'calibr8-cookie-compliance',
      'class' => [],
    ]),
    '#notification_message' => [
      '#markup' => $config->get('notification_message')['value'],
    ],
    '#noconsent_button_label' => [
      '#markup' => $config->get('noconsent_button_label'),
    ],
    '#consent_button_label' => [
      '#markup' => $config->get('consent_button_label'),
    ]
  ];

  // Render markup.
  $markup = \Drupal::service('renderer')->renderRoot($html_info);

  $attachments['#attached']['library'][] = 'calibr8_cookie_compliance/calibr8_cookie_compliance';
  $attachments['#attached']['drupalSettings']['calibr8_cookie_compliance'] = [
    'markup' => $markup,
    'cookie_expiration' => Xss::filter($config->get('cookie_expiration')),
    'cookie_consent_value' => Xss::filter($config->get('cookie_consent_value')),
    'cookie_noconsent_value' => Xss::filter($config->get('cookie_noconsent_value')),
  ];
}


/**
 * Implements hook_theme().
 */
function calibr8_cookie_compliance_theme() {
  return [
    'calibr8_cookie_info' => [
      'template' => 'calibr8_cookie_compliance_info',
      'variables' => [
        'attributes' => [],
        'notification_message' => NULL,
        'noconsent_button_label' => NULL,
        'consent_button_label' => NULL,
      ],
    ],
    'calibr8_cookie_compliance_status' => [
      'template' => 'calibr8_cookie_compliance_status',
      'variables' => [
        'status_text' => NULL,
        'consent_text' => NULL,
        'noconsent_text' => NULL,
        'consent_link_text' => NULL,
        'noconsent_link_text' => NULL,
      ],
    ],
    'calibr8_cookie_compliance_delete' => [
      'template' => 'calibr8_cookie_compliance_delete',
      'variables' => [
        'delete_text' => NULL,
        'delete_button_text' => NULL,
        'delete_cookie_successful_text' => NULL,
      ],
    ],
  ];
}
