<?php

/**
 * @file
 * Calibr8 Cookie Compliance module.
 */

use Drupal\Core\Template\Attribute;
use Drupal\Core\StringTranslation\TranslatableMarkup;

/**
 * Implements hook_page_attachments().
 */
function calibr8_cookie_compliance_page_attachments(&$attachments) {

  // Get config.
  $config = \Drupal::config('calibr8_cookie_compliance.settings');

  // Create render array.
  $html_info = [
    '#theme' => 'calibr8_cookie_info',
    '#attributes' => new Attribute([
      'id' => 'calibr8-cookie-compliance',
      'class' => [],
    ]),
    '#notification_message' => [
      '#markup' => new TranslatableMarkup($config->get('notification_message')['value']),
    ],
    '#disagree_button_label' => [
      '#markup' => new TranslatableMarkup($config->get('disagree_button_label')),
    ],
    '#agree_button_label' => [
      '#markup' => new TranslatableMarkup($config->get('agree_button_label')),
    ]
  ];

  // Render markup.
  $markup = \Drupal::service('renderer')->renderRoot($html_info);

  $attachments['#attached']['library'][] = 'calibr8_cookie_compliance/calibr8_cookie_compliance';
  $attachments['#attached']['drupalSettings']['calibr8_cookie_compliance'] = [
    'markup' => $markup,
    'cookie_expiration' => $config->get('cookie_expiration'),
  ];
}


/**
 * Implements hook_theme().
 */
function calibr8_cookie_compliance_theme() {
  return [
    'calibr8_cookie_info' => [
      'variables' => [
        'attributes' => [],
        'notification_message' => [],
        'disagree_button_label' => [],
        'agree_button_label' => [],
      ],
      'template' => 'cookie_info',
    ],
  ];
}
