calibr8_cookie_compliance.settings:
  type: config_object
  label: 'Calibr8 Cookie Compliance settings'
  mapping:
    notification_message:
      type: mapping
      label: 'Notification message'
      mapping:
        value:
          type: text
          label: 'Value'
        format:
          type: string
          label: 'Text format'
    status_text:
      type: mapping
      label: 'Cookie status text'
      mapping:
        value:
          type: text
          label: 'Value'
        format:
          type: string
          label: 'Text format'
    disagree_button_label:
      type: label
      label: 'Disagree button label'
    agree_button_label:
      type: label
      label: 'Agree button label'
    cookie_agree_value:
      type: integer
      label: 'Cookie agree value'
    cookie_disagree_value:
      type: integer
      label: 'Cookie disagree value'
    cookie_agree_link_text:
      type: label
      label: 'Agree link text'
    cookie_disagree_link_text:
      type: label
      label: 'Disagree link text'
    cookie_agree_status_text:
      type: label
      label: 'Agree status text'
    cookie_disagree_status_text:
      type: label
      label: 'Disagree status text'