calibr8_cookie_compliance.settings:
  type: config_object
  label: 'Calibr8 Cookie Compliance settings'
  mapping:
    notification_message:
      type: mapping
      label: 'Notification message'
      maping:
        value:
          type: text # translatable by default.
          translatable: true
          label: 'Value'
        format:
          type: string
          label: 'Text format'
    status_text:
      type: mapping
      label: 'Cookie status text'
      maping:
        value:
          type: text
          translatable: true
          label: 'Value'
        format:
          type: string
          label: 'Text format'
    disagree_button_label:
      type: text # translatable by default.
      translatable: true
      label: 'Disagree button label'
    agree_button_label:
      type: text # translatable by default.
      translatable: true
      label: 'Agree button label'
    cookie_agree_link_text:
      type: text
      translatable: true
      label: 'Agree link text'
    cookie_disagree_link_text:
      type: text
      translatable: true
      label: 'Disagree link text'