calibr8_cookie_compliance.settings:
  type: config_object
  label: 'Calibr8 Cookie Compliance settings'
  mapping:
    notification_message:
      type: mapping
      label: 'Notification message'
      mapping:
        value:
          type: text
          label: 'Value'
        format:
          type: string
          label: 'Text format'
    consent_button_label:
      type: label
      label: 'Consent button label'
    noconsent_button_label:
      type: label
      label: 'No consent button label'
    status_text:
      type: mapping
      label: 'Status message'
      mapping:
        value:
          type: text
          label: 'Value'
        format:
          type: string
          label: 'Text format'
    cookie_consent_status_text:
      type: label
      label: 'Consent status text'
    cookie_noconsent_status_text:
      type: label
      label: 'No consent status text'
    cookie_consent_link_text:
      type: label
      label: 'Cookie consent link text'
    cookie_noconsent_link_text:
      type: label
      label: 'Cookie noconsent link text'
    delete_text:
      type: mapping
      label: 'Delete message'
      mapping:
        value:
          type: text
          label: 'Value'
        format:
          type: string
          label: 'Text format'
    delete_button_text:
      type: label
      label: 'Cookie delete button text'
    delete_cookie_successful_text:
      type: label
      label: 'Cookie delete success message'
